### ISSUE TITLE
BUG: [AnyMemberPlugin] 成功加入DAO后，状态没有变成已加入

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-dao-frontend#112]
成功加入DAO后，状态没有变成已加入

![image](https://user-images.githubusercontent.com/1449069/204825490-87b233ad-ac0f-4c7b-9f97-ad956d743529.png)

**Comment by wow-sven** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/6805130/204853921-1ef87142-5705-4989-b7fb-75118ba84935.png">

这里不会马上更新，我可以加一个监听。不过网络不好的话，还是会这样

**Comment by wow-sven** [comment]
刷新就会是加入状态

**Comment by wow-sven** [comment]
这里改掉了
