### ISSUE TITLE
BUG: DAO创建，样式错位

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-dao-frontend#17]
在创建DAO时，如果是小屏，提案配置信息的Label会超出显示区域

![image](https://user-images.githubusercontent.com/1449069/202722938-ab114768-c92d-4fe4-95ac-9063a4a199ae.png)

**Comment by wow-sven** [comment]
https://github.com/starcoinorg/starcoin-dao-frontend/pull/26 finish
