### ISSUE TITLE
Feature: 实现 AnyMemberPlugin

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-dao-frontend#20]
如果一个DAO安装了AnyMemberPlugin，那么任何人都可以点击加入按钮，将自己添加为DAO成员
将自动获得1个SBT的投票权利。

相关代码：https://github.com/starcoinorg/starcoin-framework/blob/main/sources/daospaceplugin/AnyMemberPlugin.move

**Comment by wow-sven** [comment]
标题未修改
