### ISSUE TITLE
Feature: [插件菜单] 重排内置插件的展示顺序

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starcoin-dao-frontend#48]
重排内置插件的展示顺序，插件管理插件放在最后面

![image](https://user-images.githubusercontent.com/1449069/203444702-306a908d-0cc1-4b66-afdb-fb3c927cdebe.png)

**Comment by wow-sven** [comment]
这个排序，先固定一个吧。如果按完备的产品角度讲，要么支持用户自定义，要么这里根据使用，插件点赞来排，现在做这一套还不是很成熟

**Comment by yubing744** [comment]
OK

**Comment by yubing744** [comment]
我想到一个点，注册菜单时，传入一个index 来排序

**Comment by wow-sven** [comment]
我改了个默认把plugins 弄到最后面的，你看行的话先顶顶

**Comment by yubing744** [comment]
可以

**Comment by yubing744** [comment]
Fixed by https://github.com/starcoinorg/starcoin-dao-frontend/pull/63
